export const LOADING = "LOADING";
export const UPDATE_FB_DATA = "UPDATE_FB_DATA";
export const SELECT_PAGE = "SELECT_PAGE";
export const SELECT_TEMPLATE = "SELECT_TEMPLATE";
export const FANPAGE_LIST_STEP = "FANPAGE_LIST_STEP";
export const SET_TEMPLATE_LIST = "SET_TEMPLATE_LIST";
export const OPEN_LIVE_TEMPLATE = "OPEN_LIVE_TEMPLATE";

